### PR TITLE
show highway=toll_gantry

### LINKED ISSUE #34: Show highway=toll_gantry
[highway=toll_gantry](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtoll_gantry)

This would presumably be shown identical to barrier=toll_booth, as I'm guessing most motorways wouldn't have both.

### PR DESCRIPTION
**Pull request by andrewharvey**
closes #34

### CODE REVIEW

**Comment by goldfndr** [comment]
Great! The line spacing at index.htm seems a bit off though, as L121 and L126 are using spaces instead of tabs.

**Comment by andrewharvey** [comment]
> Great! The line spacing at index.htm seems a bit off though, as L121 and L126 are using spaces instead of tabs.

Sorry my editor didn't pick that up. Fixed now.

**Comment by goldfndr** [comment]
That looks better, thanks. There are a few inconsistencies in the file but I don't know in what direction the maintainer wants to go, so to speak. :)

**Comment by andrewharvey** [comment]
> There are a few inconsistencies in the file but I don't know in what direction the maintainer wants to go, so to speak. :)

I don't know either, but could you elaborate?

**Comment by goldfndr** [comment]
Sometimes each of the <tr> </tr> pair is on the same line as the <table> </table> pair, sometimes not. But I think I just haven't looked closely enough, it probably makes more sense when looking at the actual rendering.

**Pull request merged**
